### ISSUE TITLE
Cura 5 update. 

### ISSUE THREAD

**Issue by lola66** [lwerner-lshigh/Dremel3D-CuraPrintr#7]
Hi, I can confirm that your plugin was working well with Cura 4.X on MacOS 12.3 and a Dremel 3d40. Would really appreciate a version compatible with Cura 5.X. 
For some reason the exact same plugin on Cura 4.X with the same settings (using backup and restore) on Windows 10/11 would not work with the 3D40... It would get as far as raising the temperature and then the pintbed, but would then stop before printing anything.  Perhaps the issue was with the "Dremel Printer Plugin" since your plugin has to do with the network connection and the issue seems to be with the printing code... 
Thanks for the good work.

**Comment by lukasmwerner** [comment]
Apologies for not responding to this issue sooner. I do find it peculiar that the 3D40 on windows 10/11 was not working as that was my testing platform. I'll have to head back to the makerspace and see what's going on there. 

Regarding support for cura 5 I created an issue #6 to track the progress. As I'm currently wrapping up school I am busy for the next few weeks and wont have too much time on my hands to work on it but ill try to keep that issue up to date with the progess.

**Comment by lukasmwerner** [comment]
@lola66 Could you try the new "beta" on the #8 pr to see if that works?

**Comment by lola66** [comment]
Hi tried it, and it crashed when clicking on the "Start on Dremed3D40" button after slicing... Here's the traceback and logs from the crash report. 

Traceback (most recent call last):
  File "UM/TaskManagement/TaskManager.py", line 142, in event
    call_event.callFunction()
  File "UM/TaskManagement/TaskManager.py", line 33, in callFunction
    self._function(*self._args, **self._kwargs)
  File "/Users/lola/Library/Application Support/cura/5.0/plugins/Dremel3D-CuraPrintr-cura-5.0-support/Dremel3D-CuraPrintr/Dremel3DOutputDevice.py", line 182, in onInstanceOnline
    if reply.error() != QNetworkReply.NoError:
AttributeError: type object 'QNetworkReply' has no attribute 'NoError'

Logs:

Thread 0x00000003182b0000 (most recent call first):
  File "threading.py", line 324 in wait
  File "zeroconf/__init__.py", line 2534 in wait
  File "zeroconf/__init__.py", line 1715 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00000003172ad000 (most recent call first):
  File "zeroconf/__init__.py", line 1369 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00000003162aa000 (most recent call first):
  File "/Applications/Ultimaker-Cura.app/Contents/MacOS/share/cura/plugins/USBPrinting/USBPrinterOutputDeviceManager.py", line 88 in _updateThread
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00000003152a7000 (most recent call first):
  File "/Applications/Ultimaker-Cura.app/Contents/MacOS/share/cura/plugins/RemovableDriveOutputDevice/RemovableDrivePlugin.py", line 61 in _updateThread
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00000003142a4000 (most recent call first):
  File "threading.py", line 324 in wait
  File "zeroconf/__init__.py", line 2534 in wait
  File "zeroconf/__init__.py", line 1715 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00000003132a1000 (most recent call first):
  File "threading.py", line 324 in wait
  File "threading.py", line 600 in wait
  File "/Applications/Ultimaker-Cura.app/Contents/MacOS/share/cura/plugins/UM3NetworkPrinting/src/Network/ZeroConfClient.py", line 81 in _handleOnServiceChangedRequests
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000000031229e000 (most recent call first):
  File "zeroconf/__init__.py", line 1369 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000000030ef00000 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM/JobQueue.py", line 98 in _nextJob
  File "UM/JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000000030defd000 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM/JobQueue.py", line 98 in _nextJob
  File "UM/JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000000030cefa000 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM/JobQueue.py", line 98 in _nextJob
  File "UM/JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000000030bef7000 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM/JobQueue.py", line 98 in _nextJob
  File "UM/JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000000030aef4000 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM/JobQueue.py", line 98 in _nextJob
  File "UM/JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x0000000309ef1000 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM/JobQueue.py", line 98 in _nextJob
  File "UM/JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x0000000308eee000 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM/JobQueue.py", line 98 in _nextJob
  File "UM/JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x0000000307eeb000 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM/JobQueue.py", line 98 in _nextJob
  File "UM/JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Current thread 0x0000000201bcd600 (most recent call first):
  File "cura/CrashHandler.py", line 396 in _logInfoWidget
  File "cura/CrashHandler.py", line 182 in _createDialog
  File "cura/CrashHandler.py", line 86 in __init__
  File "cura_app.py", line 164 in exceptHook
  File "UM/Qt/QtApplication.py", line 403 in exec
  File "cura/CuraApplication.py", line 879 in run
  File "cura_app.py", line 238 in <module>

**Comment by lukasmwerner** [comment]
This has been confirmed working in pr #8 and issue #6 so will close here and keep commenting available in #6
